url: https://alanverdugo.github.io/
name: Kippel
description: No one can win against kippel.
theme: jekyll-theme-hacker
#remote_theme: ariestiyansyah/naringu
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
