url: https://alanverdugo.github.io/
name: Kippel
description: No one can win against kippel.
markdown: kramdown
theme: jekyll-theme-hacker
#remote_theme: ariestiyansyah/naringu

plugins:
  - jekyll-remote-theme
